"""First migration

Revision ID: 8531236a7721
Revises: 2b3e25b63708
Create Date: 2020-09-03 19:27:21.372880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8531236a7721'
down_revision = '2b3e25b63708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
